# Site settings
title: 银杏花开
email: dolphineor@gmail.com
description: >
  dolphineor's blog based on Github Pages and Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dolphineor.info" # the base hostname & protocol for your site
github_username:  dolphineor

# Build settings
markdown: kramdown
