#
# Basic settings.
#
url: "http://dolphineor.info" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
title: 银杏花开
description: dolphineor's blog based on Github Pages and Jekyll.
avatar: /assets/img/ogp.png

#
# Icons
#
icons:
  rss: true
  email: dolphineor@gmail.com
  github: dolphineor
  bitbucket:
  twitter:
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin:  # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: UA-65215123-1
baidu_statistics: 95bf3dd62ffc8bc36e27cf49c28aac9f
huiyan_statistics: 865139a5b3567f8a57a656f8dd91bb7a
disqus:

#
# Timezone.
#
timezone: Asia/Chongqing

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons: false
ogp:
  image_url: http://qckanemoto.github.io/jekyll-qck-theme/assets/img/ogp.png
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Gems.
#
#gems:
#  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: redcarpet
redcarpet:
  extensions: ["autolink", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes", "no_intra_emphasis"]
highlighter: pygments

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
